# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Stock project sales.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 700)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 160, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DashboardButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DashboardButton.sizePolicy().hasHeightForWidth())
        self.DashboardButton.setSizePolicy(sizePolicy)
        self.DashboardButton.setSizeIncrement(QtCore.QSize(0, 10))
        self.DashboardButton.setObjectName("DashboardButton")
        self.verticalLayout.addWidget(self.DashboardButton)
        self.Salesbutton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Salesbutton.setObjectName("Salesbutton")
        self.verticalLayout.addWidget(self.Salesbutton)
        self.ReportsButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ReportsButton.setObjectName("ReportsButton")
        self.verticalLayout.addWidget(self.ReportsButton)
        self.InventoryButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.InventoryButton.setObjectName("InventoryButton")
        self.verticalLayout.addWidget(self.InventoryButton)
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(160, 0, 1141, 651))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DashboardButton.setText(_translate("MainWindow", "Dashboard"))
        self.Salesbutton.setText(_translate("MainWindow", "Sales"))
        self.ReportsButton.setText(_translate("MainWindow", "Reports"))
        self.InventoryButton.setText(_translate("MainWindow", "Inventory"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
